/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "d9182fe43730b84d59598f460319930eefdaeca7"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
